name: "🎬 Auto Generate Combined Playlist"

on:
  schedule:
    # প্রতি ৩০ মিনিটে (UTC সময় অনুযায়ী, বাংলাদেশে +6 ঘন্টা)
    - cron: "0,30 * * * *"
  workflow_dispatch: {}    # চাইলে ম্যানুয়ালি রান করা যাবে

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies (if any)
        run: |
          pip install --upgrade pip

      - name: Generate Combined Playlist
        run: |
          python3 generate_m3u.py

      - name: Commit & Push Updated Playlist
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add combined.m3u
          git diff-index --quiet HEAD || git commit -m "🔁 Auto-updated combined.m3u"
          git push
