name: Public Workflow Scraper

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Public Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cloudscraper beautifulsoup4

    - name: Fetch Python Script from Private Repo
      run: |
        git clone https://${{ secrets.GH_PAT }}@github.com/sm-monirulislam/SM-Live-TV-Secret-Project-EXP.git private_code
        cp private_code/ott_scraper.py ./
        rm -rf private_code

    - name: Run Scraper Script
      run: python ott_scraper.py
      
    - name: Clean up Python Script
      run: rm -f ott_scraper.py

    - name: Commit and Push M3U Files
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add sm_movie2.m3u Ott_Bnagla.m3u
        git diff --quiet && git diff --staged --quiet || (git commit -m "⚡ M3U Playlists Auto-updated [$(date)]" && git push)
